#!/bin/bash
#
#BSUB -q 52-small
#BSUB -W 00:20
#BSUB -J cp2k-test
#BSUB -o cp2k.%J.stdout
#BSUB -e cp2k.%J.stderr
#BSUB -n 28
#BSUB -R "span[ptile=28]"

# add modulefiles
module load intel/17.5.239 mpi/intel/2017.5.239
module load gcc/9.3.0
module load cp2k/8.2-gpu

mpiexec.hydra cp2k.popt input.inp > output.out
